name: Test with uv

on:
  push:

jobs:
  uv:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - run: sudo apt-get update && sudo apt-get install -qqy libegl1-mesa-dev

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13

      - run: uv sync

      - run: uv pip freeze

      - run: uv run hello.py
